### PR TITLE
Adjust CSS to style on hover like on keyboard-based selection

### PR DESCRIPTION
**Pull request by rrrnld**
Thanks for enabling click-to-complete! This PR adds the selection styles for mouse-based selection.

### CODE REVIEW

**Comment by rrrnld** [comment]
Note that there's an edge case where you already used keyboard-based selection and hove over it with the mouse. You can now have two highlighted list elements - which is fine I think, since both pressing enter or clicking would initialize some action.

**Comment by snowgoon88** [comment]
So mixing keyboard and mouse is confusing since you could be surprised of the effect of ENTER : one of the two selected option will be actually selected.
- (easy) could it be possible that hover leads to different color highlight ?
- (better but more work) I guess I could also add callback to "hover" to changer the index of the selection previously made by keyboard, but then must also decide what to do if/when the mouse leave the popup : keep the last selection ?

Any other option ? Or opinion ?

**Comment by snowgoon88** [comment]
In fact I did try the callback option. See branch mouse_integration in my repos.

**Comment by saqimtiaz** [comment]
> In fact I did try the callback option. See branch mouse_integration in my repos.

I vote for the callback implementation.

**Comment by snowgoon88** [comment]
So the callback implementation has been added to the 0.9.3 version.
Thanks everyone.

**Pull request merged**
