### PR TITLE
Updated engines to inherit from original framed.js and simple.js

### PR DESCRIPTION
**Pull request by saqimtiaz**
This pull requests changes the framed.js and simple.js in the plugin to inherit from the core versions. This not only reduces the size of the plugin but should make future maintenance and compatibility with new core versions easier.

Edit: pull request updated to add a patch for the core Edit widget, to enable the same autocomplete features. This means that new users of the plugin will no longer need to change their editor type to comptext, which is a usability win.

### CODE REVIEW

**Comment by snowgoon88** [comment]
Is there a second pull request coming or did you eventually merged the two together ?

**Comment by saqimtiaz** [comment]
@snowgoon88 both are merged here. It made more sense this way.

**Comment by snowgoon88** [comment]
Ok, all this seems very fine. Thanks for doing this.

If I understand correctly, some more "actions" have to be taken to ensure backward compatibility (because the old edit-comptext is not exported anymore). Since you have a better mastery of JS than me, any hint of how to do that efficiently ?? (for my personal enlightment at least)

BTW, do you think backward compatibility is important ?

Does that mean that
1) new user just have to add the plugin, without the need to specify a new editor in their TW5 config ? => That means I have to change/adapt the doc. Right ?
2) the user cannot chose to revert to an editor with no completion, apart by removing the plugin ? Does removing the plugin really remove the completion capability ?

[Sorry, it's kind of my first pull-request ever, so... I'll try to checkout locally in the week, but It's been a long time since I've use the node development environment for TW5 that it might take some time.]

**Comment by saqimtiaz** [comment]
@snowgoon88 firstly, no worries, take your time and feel free to ask questions. 

To make it easier for you test, I have also uploaded a demo of the updated plugin code here:
https://saqimtiaz.github.io/sq-tw/comptext.html

You can also import this plugin into your own wiki (after making a backup) to test the features.

- This should be entirely backwards compatible already.  I think you can test it and if it works, just merge it. The only changes you should need to make are for documentation.
- edit-comptext is still available.
- However, users can now also get the same behaviour with the edit widget, which is what is used in the default edit template in TiddlyWiki. 
- so old users of the plugin will have full backwards compatibility. New users don't need to change the editor in the TW5 config. But if they want to manually create an extra edit field with autocomplete, they can still use edit-comptext

I will try to explain the changes in the code:

1. Instead of copy and modifying simple.js and framed.js, we only subclass them and inherit from them, and add our extra code. This means we get automatic upgrades when the core upgrades. Already some extra features of the edit-text widget were not available in edit-comptext. In the future this will not be a problem.
2. We override the edit widget in `edittext-coretweak.js`, to also add the autocomplete features when the text field is being edited. This means that for users who want to edit TW with the default edit template, which is most users, they do not need to do any extra configuration steps to get autocomplete.

**Comment by saqimtiaz** [comment]
PS: removing or disabling the plugin will remove the autocomplete ability.

**Comment by snowgoon88** [comment]
Hello, sorry I took some time.

So, I tested the PullRequest and it works fine on version 5.1.22 of TW5. 

I tested on version 5.1.13 (the old one I'm using at home because... I'm lazy) and it does not work. => no completion, even after I upload your plugin from https://saqimtiaz.github.io/sq-tw/comptext.html, save and reload the TWiki...
Not very important, but I have to maintain an old version, then, for people like me that stick too long with older version of TW5.

Any idea of what may explain this difference in behavior ?

Can it be linked with the fact that I do not understand how the anonymous function of "edittext-coretweak." is run ? I mean, I do not see where/when this function is called ? Maybe the newer version of TW5 does load/call automatically every files of the plugin, something which is not done by the 5.13 version ??

Snow

**Comment by saqimtiaz** [comment]
@snowgoon88 I will investigate with TW 5.1.13 in the coming days and get back to you. There must have been a core change that is causing an issue.

the edittext-coretweak has a module-type of widget-subclasss, so this is executed by TW after all the plugins are all loaded and before the UI is rendered. You are probably right that this is the issue, because I think subclassing was added after 5.1.13.

**Comment by saqimtiaz** [comment]
Can you confirm that the autocomplete still works in 5.1.13 if the editor type is set to comptext?

The only thing that should be not working in 5.1.13 is the automatic adding of autocomplete without changing the editor type.

**Comment by snowgoon88** [comment]
Wow, you are quite reactive.

Yes, setting 'comptext' as the editor type in 5.13 does the job. So it seems only the automatic tweak of the editor class is the only missing thing. And, I do not think this is a real problem in fact.

**Comment by saqimtiaz** [comment]
You caught me at a good time! :)

Yes, I think the same version is OK for current TW version and older. On the current TW you get the extra feature to get autocomplete without changing the editor type.

**Comment by snowgoon88** [comment]
OK. Lets merge...
Thanks for everything

**Pull request merged**
